@api = http://localhost:3000

###
GET {{api}}/getUsers
Content-Type: application/json

{
}

###
//todos los campos son requeridos
POST {{api}}/validateUser
Content-Type: application/json

{
    "mail": "jhon@gmail.com",
    "password": "admin"
}
###
//todos los campos son requeridos
POST {{api}}/insertUser
Content-Type: application/json

{
    "name": "Jhon",
    "mail": "jhon@gmail.com",
    "password": "admin"
}
###
//todos los campos pueden ser opcionales, menos id
PUT {{api}}/updateUser
Content-Type: application/json

{
    "id": "4",
    "name": "Jhonatan",
    "mail": "jhon@gmail.com",
    "password": "admin"
}

###
//solo se manda id en URL
GET {{api}}/getUser/1

// REQUEST PARA CAMBIO DE STATUS PARA CUALQUIER TABLA
###
//todos los campos son requeridos
PUT {{api}}/updateStatus
Content-Type: application/json

{
    "id": "1",
    "condition": true,
    "table_name": "tbUser"
}




###
//REQUEST PARA TABLA METHODPAYMENT
//todos los campos son requeridos
POST  {{api}}/insertMethodPayment
Content-Type: application/json

{
    "name": "contado",
    "user_id": "1"
}

###
//todos los campos son requeridos
PUT  {{api}}/updateMethodPayment
Content-Type: application/json

{
    "id": "1",
    "name": "contados"
}

###
//REQUEST PARA TABLA tbService
//todos los campos son requeridos
POST  {{api}}/insertService
Content-Type: application/json

{
    "name": "Servicio 1",
    "description": "Mantenimiento de PC",
    "user_id": "1"
}

###
//solo id es obligatorio, los demas son opcionales
PUT  {{api}}/updateService
Content-Type: application/json

{
    "id": "1",
    "name": "servicio 2",
    "description": "servicio"
}


###
//REQUEST PARA TABLA tbServicePrice
//todos los campos son requeridos
POST  {{api}}/insertServicePrice
Content-Type: application/json

{
    "service_id": "1",
    "price": "120.50"
}

###
//solo id es obligatorio, los demas son opcionales
PUT  {{api}}/updateServicePrice
Content-Type: application/json

{
    "id": "1",
    "service_id": "1",
    "price": 205.35
}


###
//REQUEST PARA TABLA tbRole
//todos los campos son requeridos
POST  {{api}}/insertRole
Content-Type: application/json

{
    "name": "admin"
}
